Move notebook spellcheck logic in a script and adapt action
This allows to use the same logic in a git pre-commit hook.
The action has to be split between notebooks and other files.

diff --git a/.github/workflows/spelling.yml b/.github/workflows/spelling.yml
--- a/.github/workflows/spelling.yml
+++ b/.github/workflows/spelling.yml
@@ -1,4 +1,4 @@
-name: Spelling check
+name: Check spelling
 
 on:
   workflow_dispatch:
@@ -9,19 +9,30 @@ jobs:
   spellcheck:
 
     runs-on: ubuntu-latest
+    defaults:
+      run:
+        shell: bash -l {0}
     strategy:
       matrix:
         python-version: [3.9]
 
     steps:
     - uses: actions/checkout@v2
-    - name: Install dependencies
+    - uses: conda-incubator/setup-miniconda@v3
+    - name: Install requirements
       run: |
-        python -m pip install -U pip
-        python -m pip install -U jupyter codespell
-    - name: Clean all notebooks
+        conda env create -f environment.yml
+    - name: Spellchecking notebooks
       run: |
-        for file in *.ipynb; do echo "${file}"; jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "${file}"; done
-    - name: Check spelling
+        conda activate introduction_gwosc_data
+        for file in *.ipynb; do
+            echo "Checking ${file}";
+            if ! ./tests/spellcheck.sh "${file}"; then
+                echo "::error file=${file},title=Error";
+                exit 1;
+            fi
+        done
+    - name: Spellchecking other files
       run: |
-        codespell . --ignore-regex "\b[a-zA-Z]{2,3}\b" -I .dictionary.txt --skip="./.git/*"
+        conda activate introduction_gwosc_data
+        codespell -I .dictionary.txt --skip="*.ipynb" .
