Adapt the logic to check versions and the action
This allows to use the same logic in a git pre-commit hook.

diff --git a/.github/workflows/versions.yml b/.github/workflows/versions.yml
--- a/.github/workflows/versions.yml
+++ b/.github/workflows/versions.yml
@@ -1,4 +1,4 @@
-name: Version check
+name: Check version
 
 on:
   workflow_dispatch:
@@ -15,13 +15,13 @@ jobs:
 
     steps:
     - uses: actions/checkout@v2
-    - name: Install dependencies
+    - name: Check versions in notebooks
       run: |
-        python -m pip install -U pip
-        python -m pip install -U jupyter
-    - name: Clean all notebooks
-      run: |
-        for file in *.ipynb; do echo "${file}"; jupyter nbconvert --ClearOutputPreprocessor.enabled=True --inplace "${file}"; done
-    - name: Check versions
-      run: |
-        python tests/check_versions.py
+        for file in *.ipynb; do
+            echo "Checking ${file}";
+            if ! ./tests/check_versions.py "${file}"; then
+                echo "::error file=${file},title=Error";
+                exit 1;
+            fi
+        done
+
